/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/room.glb 
*/

import React, { useEffect, useRef } from "react";
import {
  useGLTF,
  useAnimations,
  useTexture,
  useVideoTexture,
} from "@react-three/drei";
import * as THREE from "three";

import { motion } from "framer-motion-3d";
import { ToneMapping } from "@react-three/postprocessing";
import { Color } from "three";
import { useDispatch, useSelector } from "react-redux";
import { setMonitorRef } from "../features/redux/slices/MonitoreRefSlice";
import { degToRad } from "three/src/math/MathUtils";

export function Room(props) {
  const dispath = useDispatch();
  const currentPage = useSelector((state) => state.camera.value);
  const monitorRef = useRef();

  const group = useRef();
  const { nodes, materials } = useGLTF("models/room.glb");

  console.log(currentPage, "ROOM");
  const texture = useTexture("textures/Baked.jpg");
  const tvTexture = useVideoTexture("textures/video.mp4");

  const monitor1Texture = useVideoTexture("textures/mon1.mp4");
  const monitor2Texture = useVideoTexture("textures/mon2.mp4");
  texture.flipY = false;
  tvTexture.flipY = false;
  monitor1Texture.flipY = false;
  monitor2Texture.flipY = false;

  texture.colorSpace = THREE.SRGBColorSpace;
  const textureMaterial = new THREE.MeshStandardMaterial({ map: texture });
  useEffect(() => {
    dispath(setMonitorRef(monitorRef.current?.uuid));
  }, [currentPage]);

  return (
    <group {...props} ref={group} dispose={null}>
      <mesh
        name="TvScreen"
        geometry={nodes.TvScreen.geometry}
        position={[-1.508, 2.427, -3.88]}
      >
        <meshBasicMaterial map={tvTexture} toneMapped={false} />
      </mesh>
      <mesh
        name="MonitorScreen"
        geometry={nodes.MonitorScreen.geometry}
        position={[0.025, 1.76, -3.331]}
        rotation={[0, -0.77, 0]}
      >
        <meshBasicMaterial map={monitor1Texture} toneMapped={false} />
      </mesh>
      <mesh
        name="ScreenMonitor2"
        geometry={nodes.ScreenMonitor2.geometry}
        position={[1.059, 1.76, -3.742]}
        rotation={[0, -1.566, 0]}
      >
        <meshBasicMaterial map={monitor2Texture} toneMapped={false} />
      </mesh>
      <motion.group
        name="Bonsai"
        position={[-1.226, 1.043, 0.917]}
        whileHover={{
          scale: 1.1,
        }}
      >
        <mesh
          name="mesh430673059"
          geometry={nodes.mesh430673059.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_1"
          geometry={nodes.mesh430673059_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_2"
          geometry={nodes.mesh430673059_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_3"
          geometry={nodes.mesh430673059_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_4"
          geometry={nodes.mesh430673059_4.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_5"
          geometry={nodes.mesh430673059_5.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_6"
          geometry={nodes.mesh430673059_6.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh430673059_7"
          geometry={nodes.mesh430673059_7.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <group
        name="Chair"
        position={[1.148, 0.522, -2.031]}
        rotation={[-Math.PI, 0.052, -Math.PI]}
      >
        <mesh
          name="Node-Mesh"
          geometry={nodes["Node-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_1"
          geometry={nodes["Node-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_2"
          geometry={nodes["Node-Mesh_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_3"
          geometry={nodes["Node-Mesh_3"].geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        name="ComputerMouse_mesh"
        geometry={nodes.ComputerMouse_mesh.geometry}
        material={textureMaterial}
        position={[1.743, 1.52, -3.101]}
        rotation={[-3.14, -0.029, -3.132]}
        scale={0.057}
      />
      <group name="FlatTv" position={[-1.508, 2.427, -3.88]}>
        <mesh
          name="mesh1257628551"
          geometry={nodes.mesh1257628551.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh1257628551_1"
          geometry={nodes.mesh1257628551_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh1257628551_2"
          geometry={nodes.mesh1257628551_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh1257628551_3"
          geometry={nodes.mesh1257628551_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh1257628551_4"
          geometry={nodes.mesh1257628551_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="FlowerPot1" position={[-3.388, 2.821, -2.499]}>
        <mesh
          name="FlowerPot2_1"
          geometry={nodes.FlowerPot2_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2_2"
          geometry={nodes.FlowerPot2_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2_3"
          geometry={nodes.FlowerPot2_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2_4"
          geometry={nodes.FlowerPot2_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="FlowerPot2" position={[-3.461, 2.821, 2.348]}>
        <mesh
          name="FlowerPot2001"
          geometry={nodes.FlowerPot2001.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2001_1"
          geometry={nodes.FlowerPot2001_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2001_2"
          geometry={nodes.FlowerPot2001_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot2001_3"
          geometry={nodes.FlowerPot2001_3.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Keyboard"
        position={[1.036, 1.589, -3.081]}
        rotation={[0, 0.374, 0]}
      >
        <mesh
          name="mesh2146178072"
          geometry={nodes.mesh2146178072.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh2146178072_1"
          geometry={nodes.mesh2146178072_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh2146178072_2"
          geometry={nodes.mesh2146178072_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh2146178072_3"
          geometry={nodes.mesh2146178072_3.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="MacBook" position={[2.251, 1.591, -3.551]}>
        <mesh
          name="mesh256948792"
          geometry={nodes.mesh256948792.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh256948792_1"
          geometry={nodes.mesh256948792_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh256948792_2"
          geometry={nodes.mesh256948792_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh256948792_3"
          geometry={nodes.mesh256948792_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh256948792_4"
          geometry={nodes.mesh256948792_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Monitor1"
        position={[0.025, 1.76, -3.331]}
        rotation={[0, -0.77, 0]}
      >
        <mesh
          ref={monitorRef}
          name="mesh941242678"
          geometry={nodes.mesh941242678.geometry}
        ></mesh>
        <mesh
          name="mesh941242678_1"
          geometry={nodes.mesh941242678_1.geometry}
        />
      </group>
      <mesh
        name="Monitor2"
        geometry={nodes.Monitor2.geometry}
        material={materials["mat23.001"]}
        position={[1.059, 1.76, -3.742]}
        rotation={[0, -1.566, 0]}
      />
      <group
        name="Plant"
        position={[3.409, 0.313, -3.244]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Plant2"
          geometry={nodes.Plant2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plant2_1"
          geometry={nodes.Plant2_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plant2_2"
          geometry={nodes.Plant2_2.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Sofa"
        position={[-1.843, 0.022, 3.081]}
        rotation={[-Math.PI / 2, 0, -3.14]}
      >
        <mesh
          name="Sofa3"
          geometry={nodes.Sofa3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Sofa3_1"
          geometry={nodes.Sofa3_1.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Table"
        position={[1.183, 0.051, -3.147]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Desk"
          geometry={nodes.Desk.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Desk_1"
          geometry={nodes.Desk_1.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        name="Table_large_circular"
        geometry={nodes.Table_large_circular.geometry}
        material={textureMaterial}
        position={[-1.235, 0, 0.917]}
        scale={148.865}
      />
      <mesh
        name="Plane_1"
        geometry={nodes.Plane_1.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane_2"
        geometry={nodes.Plane_2.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane_3"
        geometry={nodes.Plane_3.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane_4"
        geometry={nodes.Plane_4.geometry}
        material={textureMaterial}
      />
    </group>
  );
}

useGLTF.preload("models/room.glb");
